#!/system/bin/sh

if [ "a$2" != "a" ];then
  gps=$2
fi

mount -o remount,rw /system
mount -o remount,rw /data
chown system system /system/etc/gps.conf
chmod 0660 /system/etc/gps.conf
case "${gps}" in
	    0)
	    if [ -f /data/gps.conf ]
	    then
	    GPS=$(cat /data/gps.conf)
	    echo "$GPS" > /system/etc/gps.conf
	    fi
	    ;;
	    1) echo "NTP_SERVER=africa.pool.ntp.org
XTRA_SERVER_1=http://xtra1.gpsonextra.net/xtra.bin
XTRA_SERVER_2=http://xtra2.gpsonextra.net/xtra.bin
XTRA_SERVER_3=http://xtra3.gpsonextra.net/xtra.bin
SUPL_HOST=supl.google.com
SUPL_PORT=7276 " > /system/etc/gps.conf
	    ;;
	    2)  echo "NTP_SERVER=asia.pool.ntp.org
XTRA_SERVER_1=http://xtra1.gpsonextra.net/xtra.bin
XTRA_SERVER_2=http://xtra2.gpsonextra.net/xtra.bin
XTRA_SERVER_3=http://xtra3.gpsonextra.net/xtra.bin
SUPL_HOST=supl.google.com
SUPL_PORT=7276 " > /system/etc/gps.conf
	    ;;
	    3) echo "NTP_SERVER=europe.pool.ntp.org
XTRA_SERVER_1=http://xtra1.gpsonextra.net/xtra.bin
XTRA_SERVER_2=http://xtra2.gpsonextra.net/xtra.bin
XTRA_SERVER_3=http://xtra3.gpsonextra.net/xtra.bin
SUPL_HOST=supl.google.com
SUPL_PORT=7276 " > /system/etc/gps.conf
	    ;;
	    4) echo "NTP_SERVER=north-america.pool.ntp.org
XTRA_SERVER_1=http://xtra1.gpsonextra.net/xtra.bin
XTRA_SERVER_2=http://xtra2.gpsonextra.net/xtra.bin
XTRA_SERVER_3=http://xtra3.gpsonextra.net/xtra.bin
SUPL_HOST=supl.google.com
SUPL_PORT=7276 " > /system/etc/gps.conf
	    ;;
	    5) echo "NTP_SERVER=oceania.pool.ntp.org
XTRA_SERVER_1=http://xtra1.gpsonextra.net/xtra.bin
XTRA_SERVER_2=http://xtra2.gpsonextra.net/xtra.bin
XTRA_SERVER_3=http://xtra3.gpsonextra.net/xtra.bin
SUPL_HOST=supl.google.com
SUPL_PORT=7276 " > /system/etc/gps.conf
	    ;;
	    6) echo "NTP_SERVER=south-america.pool.ntp.org
XTRA_SERVER_1=http://xtra1.gpsonextra.net/xtra.bin
XTRA_SERVER_2=http://xtra2.gpsonextra.net/xtra.bin
XTRA_SERVER_3=http://xtra3.gpsonextra.net/xtra.bin
SUPL_HOST=supl.google.com
SUPL_PORT=7276 " > /system/etc/gps.conf
	    ;;
	esac

mount -o remount,ro /system

echo $gps
