#!/system/bin/sh

if [ "a$3" == "a" ];then
  evalcmd='eval "echo \$GPUTHRESHOLD$2"'
  eval $evalcmd
else
  evalcmd='eval "GPUTHRESHOLD$2=$3"'
  eval $evalcmd
  evalcmd='eval "echo \$GPUTHRESHOLD$2"'
  eval $evalcmd
    echo $GPUTHRESHOLD1UP > /sys/module/mali/parameters/step0_up
    echo $GPUTHRESHOLD2DOWN > /sys/module/mali/parameters/step1_down
    echo $GPUTHRESHOLD2UP > /sys/module/mali/parameters/step1_up
    echo $GPUTHRESHOLD3DOWN > /sys/module/mali/parameters/step2_down
    echo $GPUTHRESHOLD3UP > /sys/module/mali/parameters/step2_up
    echo $GPUTHRESHOLD4DOWN > /sys/module/mali/parameters/step3_down
fi
